### ISSUE TITLE
Could not pass event InventoryClickEvent to AdvancedKitsReloaded 

### ISSUE THREAD

**Issue by Dovencio** [TryHardDood/AdvancedKitsReloaded#16]
Whenever I attempt to create and click on anything in the create GUI the items there act like normal items and the error below appears \\/

```
[20:08:21] [Server thread/ERROR]: Could not pass event InventoryClickEvent to AdvancedKitsReloaded v3.0.29-32
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[custom.jar:git-Bukkit-cb61ac0]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom.jar:git-Bukkit-cb61ac0]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [custom.jar:git-Bukkit-cb61ac0]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [custom.jar:git-Bukkit-cb61ac0]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1770) [custom.jar:git-Bukkit-cb61ac0]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) [custom.jar:git-Bukkit-cb61ac0]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) [custom.jar:git-Bukkit-cb61ac0]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [custom.jar:git-Bukkit-cb61ac0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [custom.jar:git-Bukkit-cb61ac0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:695) [custom.jar:git-Bukkit-cb61ac0]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360) [custom.jar:git-Bukkit-cb61ac0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650) [custom.jar:git-Bukkit-cb61ac0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554) [custom.jar:git-Bukkit-cb61ac0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory;
	at hu.tryharddood.advancedkits.MenuBuilder.inventory.InventoryListener.onInventoryClick(InventoryListener.java:98) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[custom.jar:git-Bukkit-cb61ac0]
	... 15 more
[20:08:22] [Server thread/ERROR]: Could not pass event InventoryClickEvent to AdvancedKitsReloaded v3.0.29-32
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[custom.jar:git-Bukkit-cb61ac0]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom.jar:git-Bukkit-cb61ac0]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [custom.jar:git-Bukkit-cb61ac0]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [custom.jar:git-Bukkit-cb61ac0]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1770) [custom.jar:git-Bukkit-cb61ac0]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) [custom.jar:git-Bukkit-cb61ac0]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) [custom.jar:git-Bukkit-cb61ac0]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [custom.jar:git-Bukkit-cb61ac0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [custom.jar:git-Bukkit-cb61ac0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:695) [custom.jar:git-Bukkit-cb61ac0]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360) [custom.jar:git-Bukkit-cb61ac0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650) [custom.jar:git-Bukkit-cb61ac0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554) [custom.jar:git-Bukkit-cb61ac0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory;
	at hu.tryharddood.advancedkits.MenuBuilder.inventory.InventoryListener.onInventoryClick(InventoryListener.java:98) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccesso
```

---Useful info---

- version: 3.0.29-36
- 1024MB allocated
- Other plugins installed (if conflicts exist ask for a list)

**Comment by benjaminforras** [comment]
Do you use spigot/bukkit or other server(Glowstone, Sponge)?

**Comment by Dovencio** [comment]
Bukkit

**Comment by Dovencio** [comment]
Anything new?

**Comment by benjaminforras** [comment]
Fixed

**Comment by Dovencio** [comment]
Sorry to bother you some more but do I need to install a new version?

**Comment by benjaminforras** [comment]
Not yet, because it's not out.

**Comment by Dovencio** [comment]
just checking because my team is stabbing me with knives attached to pitchforks. Wondering if it was on a server's end or something.

**Comment by benjaminforras** [comment]
Once I have enough time I'll push a release
