### ISSUE TITLE
NPE on startup

### ISSUE THREAD

**Issue by SlimeDog** [TryHardDood/AdvancedKitsReloaded#19]
## What steps will reproduce the problem?  
start-up server

## What were you expecting to happen? What happened instead?  
no NPE

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
1.0.0

## What Spigot version are you using? *Type /version*  
1.11.2 latest pull

## What plugins are you using? *Type /plugins*  
Lots

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
> [10:22:00] [Server thread/ERROR]: Error occurred while enabling AdvancedKitsReloaded v1.0.0 (Is it up to date?)
java.lang.NullPointerException
        at hu.tryharddevs.advancedkits.utils.ItemStackUtil.deserializeItem(ItemStackUtil.java:78) ~[?:?]
        at hu.tryharddevs.advancedkits.utils.ItemStackUtil.itemFromString(ItemStackUtil.java:97) ~[?:?]
        at hu.tryharddevs.advancedkits.kits.KitManager.lambda$loadKits$0(KitManager.java:68) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_121]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_121]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_121]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_121]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_121]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_121]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_121]
        at hu.tryharddevs.advancedkits.kits.KitManager.loadKits(KitManager.java:68) ~[?:?]
        at hu.tryharddevs.advancedkits.AdvancedKitsMain.onEnable(AdvancedKitsMain.java:90) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.2.jar-2017-04-26-0646:git-Spigot-a3f6ea5-2453830]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar-2017-04-26-0646:git-Spigot-a3f6ea5-2453830]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar-2017-04-26-0646:git-Spigot-a3f6ea5-2453830]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.2.jar-2017-04-26-0646:git-Spigot-a3f6ea5-2453830]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.2.jar-2017-04-26-0646:git-Spigot-a3f6ea5-2453830]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.11.2.jar-2017-04-26-0646:git-Spigot-a3f6ea5-2453830]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.11.2.jar-2017-04-26-0646:git-Spigot-a3f6ea5-2453830]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.11.2.jar-2017-04-26-0646:git-Spigot-a3f6ea5-2453830]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar-2017-04-26-0646:git-Spigot-a3f6ea5-2453830]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.11.2.jar-2017-04-26-0646:git-Spigot-a3f6ea5-2453830]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

## Additional information?  *(Did it work in previous versions? etc.)*
3.0.29-36 worked fine

**Comment by benjaminforras** [comment]
Could you post one of your kit's yml file?

**Comment by SlimeDog** [comment]
They are not changed from 3.0.29-36. I did not read indication that changes were required.
Example kit: https://pastebin.com/AGGFeuPv

**Comment by benjaminforras** [comment]
The new version serializes the items, armors to prevent dataloss. (Missing nbt tags etc.)
Will push a fix soon. Thanks for reporting.

**Comment by SlimeDog** [comment]
All my kits are very similar in structure. So fix for one should fix them all. :)
