### ISSUE TITLE
NPE adding flag

### ISSUE THREAD

**Issue by SlimeDog** [TryHardDood/AdvancedKitsReloaded#28]
## What steps will reproduce the problem?  
1. Remove flags per instruction in wiki.
2. Start server.
3. Execute command:
> /kit flag blueLeader icon EMERALD_BLOCK

## What were you expecting to happen? What happened instead?  
Expect: Flag to be set.
Result: Errors in-game and in log.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
1.0.2

## What Spigot version are you using? *Type /version*  
1.11.2 latest

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
> 23:30:42 WARN]: java.lang.NullPointerException
[23:30:42 WARN]:        at hu.tryharddevs.advancedkits.commands.FlagCommand.flagCommand(FlagCommand.java:50)
[23:30:42 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:30:42 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:30:42 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:30:42 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[23:30:42 WARN]:        at hu.tryharddevs.advancedkits.CommandManager.runCommand(CommandManager.java:295)
[23:30:42 WARN]:        at hu.tryharddevs.advancedkits.CommandManager.onCommand(CommandManager.java:166)
[23:30:42 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[23:30:42 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[23:30:42 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
[23:30:42 WARN]:        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1354)
[23:30:42 WARN]:        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189)
[23:30:42 WARN]:        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[23:30:42 WARN]:        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[23:30:42 WARN]:        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[23:30:42 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:30:42 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:30:42 WARN]:        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[23:30:42 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
[23:30:42 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[23:30:42 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[23:30:42 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[23:30:42 WARN]:        at java.lang.Thread.run(Thread.java:745)

## Additional information?  *(Did it work in previous versions? etc.)*
In-game error:
> An exception occured [sic]. Please contact a member of staff and tell them!

**Comment by benjaminforras** [comment]
That flag is does not exist yet

**Comment by benjaminforras** [comment]
Could you post the modified kit yml?
