### ISSUE TITLE
The plugin won't work with the latest Spigot release

### ISSUE THREAD

**Issue by waterquarks** [TryHardDood/AdvancedKitsReloaded#29]
## What steps will reproduce the problem?  
Starting the server.

## What were you expecting to happen? What happened instead?  
The plugin to work, it didn't.
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
Latest release: v1.0.3-pre2.
## What Spigot version are you using? *Type /version*  
Also de latest release: CraftBukkit version git-Spigot-a3f6ea5-a2af8f0 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT).
## What plugins are you using? *Type /plugins*  
[Server] INFO Plugins (39): dynmap, WorldEdit, CustomShields, FirstJoinPlus, MythicLib, ChatControl, WorldBorder, NametagEdit, BuycraftX, MessageAnnouncer, Votifier, Multiverse-Core, ProtocolLib, LibsDisguises, AdvancedPortals, Friends3_0, VotingPlugin, SuperTrails, PermissionsEx, RandomTeleport, LiteJoin, AdvancedKitsReloaded, Tablist, Vault, ServerListPlus, CommandBook, ColoredAnvils, Orebfuscator4, HolographicDisplays, WorldGuard, HideAndCustomPlugins, Citizens, SignColors, MythicMobs, CraftBook, Denizen, Quests, GriefPrevention, JDynmapGriefPrevention
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/kAyS9sLN
## Additional information?  *(Did it work in previous versions? etc.)*
It worked on previous versions, latest release won't work with the most recent Spigot update.

**Comment by benjaminforras** [comment]
Could you share the full error message?

**Comment by waterquarks** [comment]
Sure, it's here: https://pastebin.com/fCnTQH5a

**Comment by benjaminforras** [comment]
Could you share the full log?

**Comment by TheIntelloBox** [comment]
Fix it please. :c

**Comment by TheIntelloBox** [comment]
[18:52:47] [Server thread/INFO]: [AdvancedKits] Enabling AdvancedKitsReloaded v1.0.3-pre
[18:52:47] [Server thread/INFO]: [AdvancedKits] Starting AdvancedKitsReloaded 1.0.3-pre
[18:52:47] [Server thread/INFO]: [AdvancedKits] Successfully hooked to PlaceholderAPI!
[18:52:47] [Server thread/INFO]: [AdvancedKits] Loading configuration.
[18:52:47] [Server thread/ERROR]: Error occurred while enabling AdvancedKitsReloaded v1.0.3-pre (Is it up to date?)
java.lang.NullPointerException
	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at hu.tryharddevs.advancedkits.AdvancedKitsMain.loadConfiguration(AdvancedKitsMain.java:103) ~[?:?]
	at hu.tryharddevs.advancedkits.AdvancedKitsMain.onEnable(AdvancedKitsMain.java:53) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by benjaminforras** [comment]
I'll push an update out soon

**Comment by TheIntelloBox** [comment]
Okay nice ! :)

**Comment by benjaminforras** [comment]
Check it out with this version: [v1.0.3-pre3](https://github.com/TryHardDood/AdvancedKitsReloaded/releases/tag/v1.0.3-pre3)

**Comment by TheIntelloBox** [comment]
Any error in the console, but in-game, the plugin doesn't work. I can't do /? AdvancedKitsReloaded, when I do /advancedkits it does nothing, when I do /kit there are the Essentials Kits...

**Comment by benjaminforras** [comment]
Can you post your full server log?

**Comment by TheIntelloBox** [comment]
LOOK ALL : https://hastebin.com/oxuyuvemoh.md

**Comment by benjaminforras** [comment]
I don't see any problem. Take a look at this page: https://github.com/TryHardDood/AdvancedKitsReloaded/wiki/4.-Commands

`AdvancedKits Reloaded v3.0.29-36.`
Turn off the updater and download the plugin again.

**Comment by TheIntelloBox** [comment]
LOOK NOW : https://hastebin.com/oxuyuvemoh.md

**Comment by benjaminforras** [comment]
As I said before. Disable autoupdate and download the plugin again. It will work
Edit: To disable autoupdate open your plugins folder search for the updater/config.yml file then disable the checks im that file. Restart your server after you disabled autoupdate

**Comment by TheIntelloBox** [comment]
I can't disable autoupdate with the new config.yml.

**Comment by benjaminforras** [comment]
It's not in the AdvancedKitsReloaded folder. It's in the Updater folder. So plugins/updater/config.yml

**Comment by TheIntelloBox** [comment]
[05:01:33] [Server thread/INFO]: [AdvancedKits] Starting AdvancedKitsReloaded 1.0.3-pre3
[05:01:33] [Server thread/INFO]: [ReflectionHelper] Version is v1_11_R1 (11101)
[05:01:33] [Server thread/INFO]: [AdvancedKits] Loading configuration.
[05:01:33] [Server thread/INFO]: [AdvancedKits] Locale: "en" | Locale file: messages_en.properties
[05:01:33] [Server thread/INFO]: [AdvancedKits] Hooking to Vault.
[05:01:33] [Server thread/INFO]: [AdvancedKits] Loading MenuAPI by ColonelHedgehog.
[05:01:33] [Server thread/INFO]: [AdvancedKits] Loading KitManager.
[05:01:33] [Server thread/INFO]: [AdvancedKits] Loaded 61 kit(s).
[05:01:33] [Server thread/INFO]: [AdvancedKits] Registering events
[05:01:33] [Server thread/INFO]: [AdvancedKits] Registering commands.
[05:01:33] [Server thread/INFO]: [AdvancedKits] Checking for updates.
[05:01:33] [Server thread/INFO]: [AdvancedKits] Finished loading AdvancedKitsReloaded 1.0.3-pre3 by TryHardDood

Doesn't work in-game.

**Comment by benjaminforras** [comment]
What doesn't work?
Have you checked out the commands? [4. Commands](https://github.com/TryHardDood/AdvancedKitsReloaded/wiki/4.-Commands)

**Comment by TheIntelloBox** [comment]
Nothing works. When I disable essentials nothing works too.
0 error in the console.

**Comment by benjaminforras** [comment]
So when you type **/kit view** it does nothing?

**Comment by TheIntelloBox** [comment]
Yes. ^^ And when Essentials is enabled it says : "The kit view doesn't exist".

**Comment by benjaminforras** [comment]
Try with this: **/akit view**

**Comment by TheIntelloBox** [comment]
It works but : http://zupimages.net/up/17/17/ujrb.jpg

**Comment by benjaminforras** [comment]
That's a problem. lol
Thanks for reporting. I'll fix it later today.

**Comment by benjaminforras** [comment]
Fixed in [v1.0.4](https://github.com/TryHardDood/AdvancedKitsReloaded/releases/tag/v1.0.4)

**Comment by waterquarks** [comment]
First of all, thank you for the amazing support. Very few devs exceed the expectations in this area.
I downloaded and installed the new latest version of the plugin, but it fails to hook into Vault, although I have also the latest version installed. 
Here is the AdvancedKitsReloaded part in the server logs:
https://pastebin.com/hrch2MwZ
Here are the full logs:
https://pastebin.com/px67qUYA
Keep up the magnificent work!

**Comment by benjaminforras** [comment]
Thanks! In your full server log I see some of the other plugins have this problem too. I'll need to investigate this. Thanks for reporting it.

**Comment by benjaminforras** [comment]
I think one of your plugins causing the problem which is affecting other plugins too.
```
[18:42:33] [Server thread/WARN]: [VotingPlugin] Failed to hook into Vault
[18:42:33] [Server thread/INFO]: [AdvancedKits] Hooking to Vault.
[18:42:33] [Server thread/INFO]: [AdvancedKits] [AdvancedKitsReloaded] - Disabled due to no Vault dependency found!
[18:42:34] [Server thread/ERROR]: [SignColors] Some features won't work, because Vault is missing!
[18:42:34] [Server thread/ERROR]: [SignColors] Please install Vault!
```
For me it's working properly. But I'll take a deeper look later today. (1:21am) :)
