### ISSUE TITLE
Error !

### ISSUE THREAD

**Issue by TheIntelloBox** [TryHardDood/AdvancedKitsReloaded#35]
[17:06:34] [Server thread/ERROR]: Failed to get Command Map. ACF will not function.
[17:06:34] [Server thread/ERROR]: Error occurred while enabling AdvancedKitsReloaded v1.1.2 (Is it up to date?)
java.lang.NoSuchFieldException: knownCommands
	at java.lang.Class.getDeclaredField(Class.java:2070) ~[?:1.8.0_72]
	at hu.tryharddevs.advancedkits.utils.afc.BukkitCommandManager.<init>(BukkitCommandManager.java:59) ~[?:?]
	at hu.tryharddevs.advancedkits.utils.afc.ACF.createManager(ACF.java:44) ~[?:?]
	at hu.tryharddevs.advancedkits.AdvancedKitsMain.onEnable(AdvancedKitsMain.java:79) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPlugins.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by benjaminforras** [comment]
Could you send me the full log? (pastebin.com)
