### ISSUE TITLE
Error ! 

### ISSUE THREAD

**Issue by TheIntelloBox** [TryHardDood/AdvancedKitsReloaded#39]
[11:25:15] [Server thread/INFO]: [AdvancedKits] Starting AdvancedKitsReloaded 1.1.3
[11:25:15] [Server thread/INFO]: [ReflectionHelper] Version is v1_11_R1 (11101)
[11:25:15] [Server thread/INFO]: [AdvancedKits] Loading configuration.
[11:25:15] [Server thread/INFO]: [AdvancedKits] Locale: "en" | Locale file: messages_en.properties
[11:25:15] [Server thread/INFO]: [AdvancedKits] Hooking to Vault.
[11:25:15] [Server thread/INFO]: [AdvancedKits] Loading KitManager.
[11:25:16] [Server thread/INFO]: [AdvancedKits] Loaded 61 kit(s).
[11:25:16] [Server thread/INFO]: [AdvancedKits] Registering events
[11:25:16] [Server thread/INFO]: [AdvancedKits] Registering commands.
[11:25:16] [Server thread/ERROR]: Failed to get Command Map. ACF will not function.
[11:25:16] [Server thread/ERROR]: Error occurred while enabling AdvancedKitsReloaded v1.1.3 (Is it up to date?)
java.lang.NoSuchFieldException: knownCommands
	at java.lang.Class.getDeclaredField(Class.java:2070) ~[?:1.8.0_72]
	at hu.tryharddevs.advancedkits.utils.afc.BukkitCommandManager.<init>(BukkitCommandManager.java:61) ~[?:?]
	at hu.tryharddevs.advancedkits.utils.afc.ACF.createManager(ACF.java:44) ~[?:?]
	at hu.tryharddevs.advancedkits.AdvancedKitsMain.onEnable(AdvancedKitsMain.java:79) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPlugins.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by benjaminforras** [comment]
Please download v1.1.4 and copy the error here again. (*This will probably show which plugin causing the problem.*)
https://github.com/TryHardDood/AdvancedKitsReloaded/releases/tag/v1.1.4

**Comment by benjaminforras** [comment]
Ref. issue: aikar/commands#25

**Comment by benjaminforras** [comment]
Closed due to no feedback
