### ISSUE TITLE
Another error furthermore.

### ISSUE THREAD

**Issue by TheIntelloBox** [TryHardDood/AdvancedKitsReloaded#44]
[10:52:09] [Server thread/INFO]: [AdvancedKits] Enabling AdvancedKitsReloaded v1.1.6
[10:52:09] [Server thread/WARN]: Enabled plugin with unregistered PluginClassLoader AdvancedKitsReloaded v1.1.6
[10:52:09] [Server thread/INFO]: [AdvancedKits] Starting AdvancedKitsReloaded 1.1.6
[10:52:09] [Server thread/INFO]: [ReflectionHelper] Version is v1_11_R1 (11101)
[10:52:09] [Server thread/INFO]: [AdvancedKits] Hooking to Vault.
[10:52:09] [Server thread/INFO]: [AdvancedKits] Loading configuration.
[10:52:09] [Server thread/INFO]: [AdvancedKits] Locale: "en" | Locale file: messages_en.properties
[10:52:09] [Server thread/INFO]: [AdvancedKits] Loading KitManager.
[10:52:09] [Server thread/INFO]: [AdvancedKits] Loaded 61 kit(s).
[10:52:09] [Server thread/INFO]: [AdvancedKits] Registering events
[10:52:09] [Server thread/INFO]: [AdvancedKits] Registering commands.
[10:52:09] [Server thread/ERROR]: [ACF] Failed to get Command Map. ACF will not function.
[10:52:09] [Server thread/ERROR]: Error occurred while enabling AdvancedKitsReloaded v1.1.6 (Is it up to date?)
java.lang.NoSuchFieldException: knownCommands
	at java.lang.Class.getDeclaredField(Class.java:2070) ~[?:1.8.0_72]
	at hu.tryharddevs.advancedkits.utils.afc.BukkitCommandManager.<init>(BukkitCommandManager.java:72) ~[?:?]
	at hu.tryharddevs.advancedkits.utils.afc.ACF.createManager(ACF.java:44) ~[?:?]
	at hu.tryharddevs.advancedkits.AdvancedKitsMain.onEnable(AdvancedKitsMain.java:86) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPlugins.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by aikar** [comment]
Re: https://github.com/aikar/commands/issues/25

Will look into this tonight.

**Comment by aikar** [comment]
Fix is pending TryHard to release a new ver.
